
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#server.path=8081
#server.servlet.context-path=/journal
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
  servlet:
    context-path: /journal

